### ISSUE TITLE
<class 'argparse.FileType'> is a FileType class object, instance of it must be passed

### ISSUE THREAD

**Issue by ngockhanh5110** [allegroai/clearml-serving#1]
I had this issue while running the very first command
` clearml-serving triton --project "serving" --name "serving example"`

` <class 'argparse.FileType'> is a FileType class object, instance of it must be passed`

**Comment by bmartinn** [comment]
Hi @ngockhanh5110 
I think the issue was solved with the `0.3.2` release.
```
pip install clearml-serving==0.3.2
```
Could you verify ?

**Comment by ngockhanh5110** [comment]
Hi there,

The issue is preserved even when I upgraded to version 0.3.2

@bmartinn

**Comment by bmartinn** [comment]
What's the python version? and OS version ?
Could you try to run with --debug and send the full log ?
```
clearml-serving --debug triton --project "serving" --name "serving example"
```

**Comment by ecm200** [comment]
I can also confirm that I get the following error as well on PYPI version 0.3.2.

I have just installed the master branch at commit **9254079** and it works perfectly.

**Comment by bmartinn** [comment]
I forgot to update here, v0.3.3 is out with a fix

```
pip install clearml-serving==0.3.3
```

**Comment by ecm200** [comment]
@bmartinn It fixed the issue for me, so I'd say the issue is closed for me, thanks!
