### ISSUE TITLE
Triton docker container failed to start due to unknown error

### ISSUE THREAD

**Issue by janesenaj** [allegroai/clearml-serving#14]
The inference task was successfully created after launching the serving services (`clearml-serving launch --queue default`).

However, it seems that the nvdia container failed to start with the following error:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
```

Using a local worker without GPU attached to the public hosting clearml server.

**Comment by jkhenning** [comment]
Hi @janesenaj,

From a quick look online, it seems this error is related to the NVIDIA driver you have installed - can you try to upgrade to a newer driver?

**Comment by qwaxys** [comment]
Closing this issue as inactive, feel free to open a new issue and link to this one.
