### ISSUE TITLE
Error triton helper file

### ISSUE THREAD

**Issue by NurrahmiM** [allegroai/clearml-serving#15]
Hello,
 I'm trying clearml serving with nvidia triton. I'm having trouble with the above error which is _FileNotFoundError: [WinError 2] The system cannot find the file specified_. Can someone help me?
![error triton helper](https://user-images.githubusercontent.com/80824031/140006355-1f9f75c5-968d-4a6e-8cda-9855395cb9b6.png)

**Comment by jkhenning** [comment]
Hi @NurrahmiM,

It looks like the `tritonserver` command cannot be found in the path. The code assumes this command is available - you'll need to make sure this command is in the system path.

**Comment by NurrahmiM** [comment]
thank you for answering the question 😆
now i got an error like the picture i attached with error _WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behavior with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv_
and then after show warning status process still running, but after I wait 15 minutes there is no further process.
Does the warning affect the running process ?
![error](https://user-images.githubusercontent.com/80824031/142840016-5fc4df36-4054-4aa2-86ac-fbbfa9cd2b32.png)

**Comment by bmartinn** [comment]
Hi @NurrahmiM 

> now i got an error like the picture i attached with error WARNING: Running pip as the 'root' user can result in broken permissions  ...

This is actually quite okay, it just means that you are running inside the container as root, which is kind of the standard.

> and then after show warning status process still running, but after I wait 15 minutes there is no further process.

Can you provide the full log (press on the "download full log" button and attach here) ?
Also can you provide the CLI command you used to spin the `clearml-serving` with?

**Comment by NurrahmiM** [comment]
hi @bmartinn ,

> Can you provide the full log (press on the "download full log" button and attach here) ?
Also can you provide the CLI command you used to spin the clearml-serving with?

Yesterday I got the above error from docker, when I retrained in the community app there was no warning like what I experienced in the docker clearml. Why did it happen?

And I also want to ask, can this clearml serving also work for the scikit learn model? if possible, how do i create a config.pbtxt file for scikit learn?

**Comment by qwaxys** [comment]
Closing this issue as inactive, feel free to open a new issue and link to this one.
