### ISSUE TITLE
Take model from clearml server via API

### ISSUE THREAD

**Issue by calvinshalim** [allegroai/clearml-serving#19]
is there any way that I can take the model from clearml server to my machine through API so I can run it locally without download it? thank you

**Comment by jkhenning** [comment]
Hi @calvinshalim ,

I assume you have the model ID? The ClearML Server contains the link to the model file (but not the model itself). Where do you store the model? Is it in the ClearML fileserver?

**Comment by calvinshalim** [comment]
hi @jkhenning , 

thank you for the reply. yes I have the model ID and it is stored in the clearml fileserver. is there a way to get the model itself through API? thank you

**Comment by jkhenning** [comment]
Well, you can use the ClearML SDK and do something like:
```python
from clearml import Model
filename = Model("<model-id>").get_local_copy()
```

**Comment by calvinshalim** [comment]
@jkhenning 
but get_local_copy() is only to get the link to the model file right? What I want is a way to get the model itself through the model ID and implement it in my project like for example in a notebook. is it possible? thank you

**Comment by jkhenning** [comment]
`get_local_copy()` downloads the model weights file locally and returns the local path where it is stored - I thought that's what you were looking for 🙂

**Comment by jkhenning** [comment]
If you modified the model locally, you can update the weights file using the SDK as well
