### ISSUE TITLE
clearml.storage - ERROR - Google cloud driver not found

### ISSUE THREAD

**Issue by Ofir-Pipl** [allegroai/clearml-serving#23]
Trying to call model endpoint where the model stored on GCP bucket, getting the error:

clearml.storage - ERROR - Google cloud driver not found. Please install driver using: pip install "google-cloud-storage>=1.13.2"

After installing manually it works.

We use the k8s version - installed with helm

**Comment by valeriano-manassero** [comment]
@Ofir-Pipl will work on this asap, it will require some time I think since I testing will be a bit time consuming.

**Comment by valeriano-manassero** [comment]
@Ofir-Pipl can you pls check allegroai/clearml-helm-charts#72 if this is what you were looking for?

**Comment by Ofir-Pipl** [comment]
@[valeriano-manassero](https://github.com/valeriano-manassero) Yes, this is what i was looking for.
Thanks for the quick response.

**Comment by valeriano-manassero** [comment]
Merged and `clearml-serving` new chart version released, enjoy! 😄
