### ISSUE TITLE
Triton inference server docker container deployment fails due to ports conflict

### ISSUE THREAD

**Issue by ecm200** [allegroai/clearml-serving#3]
I've been following the example on Keras, but using a PyTorch model.
I have setup a serving instance with the following command:

` clearml-serving triton --project "Caltech Birds/Deployment" --name "ResNet34 Serving"`

I then added the model endpoint and the model ID of the model to be served:

`clearml-serving triton --endpoint "resent34_cub200" --model-id "57ed24c1011346d292ecc9e797ccb47e"`

The model was trained using an experiment script which included the generation of a `config.pbtxt` configuration file at the time of completion of model training. This was connected to the experiment configuration as per the Keras example, and resulted in the following configuration being added to the experiment:

```yaml
            platform: "pytorch_libtorch"
            input [
                {
                    name: "input_layer"
                    data_type: TYPE_FP32
                    dims: [ 3, 224, 224 ]
                }
            ]
            output [
                {
                    name: "fc"
                    data_type: TYPE_FP32
                    dims: [ 200 ]
                }
            ]
```

I then created a queue on a GPU compute node (as the model requires GPU resource):

` clearml-agent daemon --queue default --gpus all --detached --docker`

 The serving endpoint is then started with the following command:

`clearml-serving launch -queue default`

I can see two items in my deployment sub-project, the service I created, and a triton serving engine inference object.

On execution, the triton serving engine inference fails with the following errors:

```shell
2021-06-08 16:28:49
task f2fbb3218e8243be9f6ab37badbb4856 pulled from 2c28e5db27e24f348e1ff06ba93e80c5 by worker ecm-clearml-compute-gpu-002:0
2021-06-08 16:28:49
Running Task f2fbb3218e8243be9f6ab37badbb4856 inside docker: nvcr.io/nvidia/tritonserver:21.03-py3 arguments: ['--ipc=host', '-p', '8000:8000', '-p', '8001:8001', '-p', '8002:8002']
2021-06-08 16:28:50
Executing: ['docker', 'run', '-t', '--gpus', 'all', '--ipc=host', '-p', '8000:8000', '-p', '8001:8001', '-p', '8002:8002', '-e', 'CLEARML_WORKER_ID=ecm-clearml-compute-gpu-002:0', '-e', 'CLEARML_DOCKER_IMAGE=nvcr.io/nvidia/tritonserver:21.03-py3 --ipc=host -p 8000:8000 -p 8001:8001 -p 8002:8002', '-v', '/tmp/.clearml_agent.ft8vulpe.cfg:/root/clearml.conf', '-v', '/tmp/clearml_agent.ssh.j9b8arhf:/root/.ssh', '-v', '/home/edmorris/.clearml/apt-cache:/var/cache/apt/archives', '-v', '/home/edmorris/.clearml/pip-cache:/root/.cache/pip', '-v', '/home/edmorris/.clearml/pip-download-cache:/root/.clearml/pip-download-cache', '-v', '/home/edmorris/.clearml/cache:/clearml_agent_cache', '-v', '/home/edmorris/.clearml/vcs-cache:/root/.clearml/vcs-cache', '--rm', 'nvcr.io/nvidia/tritonserver:21.03-py3', 'bash', '-c', 'apt-get update ; apt-get install -y git ; . /opt/conda/etc/profile.d/conda.sh ; conda activate base ; [ ! -z $LOCAL_PYTHON ] || export LOCAL_PYTHON=python3 ; $LOCAL_PYTHON -m pip install -U "pip<20.2" ; $LOCAL_PYTHON -m pip install -U clearml-agent ; cp /root/clearml.conf /root/default_clearml.conf ; NVIDIA_VISIBLE_DEVICES=all $LOCAL_PYTHON -u -m clearml_agent execute --disable-monitoring  --id f2fbb3218e8243be9f6ab37badbb4856']
2021-06-08 16:28:55
docker: Error response from daemon: driver failed programming external connectivity on endpoint wonderful_galileo (0c2feca5684f2f71b11fa1e8da4550d42b23c456e52ba0069d0aae64cd75f55b): Error starting userland proxy: listen tcp4 0.0.0.0:8001: bind: address already in use.
2021-06-08 16:28:55
Process failed, exit code 125
```

This could be related to the parameters of the Triton docker container, which includes both `ipc=host` and specific port mapping `'-p', '8000:8000'`. This appears to be specified in the `ServingService.launch_service()` method from the `ServingService` Class from the `clearml-serving`  package would appear to have both been specified as hard coded for the Triton docker container: 

```python
def launch_engine(self, queue_name, queue_id=None, verbose=True):
        # type: (Optional[str], Optional[str], bool) -> None
        """
        Launch serving engine on a specific queue
        :param queue_name: Queue name to launch the engine service running the inference on.
        :param queue_id: specify queue id (unique stand stable) instead of queue_name
        :param verbose: If True print progress to console
        """
        # todo: add more engines
        if self._engine_type == 'triton':
            # create the serving engine Task
            engine_task = Task.create(
                project_name=self._task.get_project_name(),
                task_name="triton serving engine",
                task_type=Task.TaskTypes.inference,
                repo="https://github.com/allegroai/clearml-serving.git",
                branch="main",
                commit="ad049c51c146e9b7852f87e2f040e97d88848a1f",
                script="clearml_serving/triton_helper.py",
                working_directory=".",
                docker="nvcr.io/nvidia/tritonserver:21.03-py3 --ipc=host -p 8000:8000 -p 8001:8001 -p 8002:8002",
                argparse_args=[('serving_id', self._task.id), ],
                add_task_init_call=False,
            )
            if verbose:
                print('Launching engine {} on queue {}'.format(self._engine_type, queue_id or queue_name))
            engine_task.enqueue(task=engine_task, queue_name=queue_name, queue_id=queue_id)
```

**Comment by jkhenning** [comment]
Hi @ecm200,

We'll make sure this is configurable 🙂

**Comment by ecm200** [comment]
Just having a play with the various docker arguments to do with the ports to see what happens.

**Comment by ecm200** [comment]
A few confusing issues to report here.

### Potential Triton Container Ports Issue Fix
Firstly, I changed the docker string argument in the `Task.create()` call of the `launch_engine()` method of the `ServingService` Class, such that only `--ipc=host` is passed.

The original string argument was as follows:

`docker="nvcr.io/nvidia/tritonserver:21.03-py3 --ipc=host -p 8000:8000 -p 8001:8001 -p 8002:8002"`

This was modified to:

`docker="nvcr.io/nvidia/tritonserver:21.03-py3 --ipc=host"`

This appears to have solved the errors regarding port bindings error which caused the job monitoring to fail last time.


### Additional CLEARML-AGENT config issues on compute resource

There were also additional issues I encountered, which were to do with the way I had configured the `clearml-agent` on the compute resource. I was launching the inference server using an agent that was previously built for training purposes. In order to get the `clearml-agent` to run in docker mode using Conda (this was due to issues with installing PyTorch using PIP, a known PyTorch issue), I modified the `clearml.conf` so that a docker image was initialized correctly to make the Conda package manager available to the execution environment:

```yaml
docker_init_bash_script = [
         "apt-get update",
         "apt-get install -y git",
         ". /opt/conda/etc/profile.d/conda.sh",
         "conda activate base",
    ]
```
**Whilst the above worked for getting PyTorch installed on a docker container for model training, it caused problems with getting the Triton server container running**.

To avoid conflicts with the Triton Inference server image, I created a fresh `clearml.conf` file in a different location and referenced that file using the `--config-file` argument of the `clearml-agent` when creating the agent for the services queue. This resulted in the Triton Inference instance loading up.

However, the model did load for the Inference Server, as it appears the model weights were not referenced properly.

```shell
Updating local model folder: /models
Error retrieving model ID 57ed24c1011346d292ecc9e797ccb47e []
```

### Questions

**I think this is possibly related to the location of the models, as the model weights are stored on an Azure Blob Storage remote storage, rather than the server.
Is this a configuration issue not referencing the remote model location correctly?**


### Triton Server Error Report
Here is the full error report from the Triton server:

```shell
Starting Task Execution:

clearml-serving - Nvidia Triton Engine Helper
ClearML results page: http://:8080/projects/779be4f4d83541d786eb839bb062fa93/experiments/79f1047d52c349d78faeb529feac837a/output/log
String Triton Helper service
{'serving_id': '27ec63d4a0744464814b76815d183df2', 'project': 'serving', 'name': 'nvidia-triton', 'update_frequency': 10, 'metric_frequency': 1, 't_http_port': None, 't_http_thread_count': None, 't_allow_grpc': None, 't_grpc_port': None, 't_grpc_infer_allocation_pool_size': None, 't_pinned_memory_pool_byte_size': None, 't_cuda_memory_pool_byte_size': None, 't_min_supported_compute_capability': None, 't_buffer_manager_thread_count': None}

Updating local model folder: /models
Error retrieving model ID 57ed24c1011346d292ecc9e797ccb47e []
Starting server: ['tritonserver', '--model-control-mode=poll', '--model-repository=/models', '--repository-poll-secs=600.0', '--metrics-port=8002', '--allow-metrics=true', '--allow-gpu-metrics=true']
I0609 11:05:09.282508 697 metrics.cc:221] Collecting metrics for GPU 0: Tesla P40

1623236714491 ecm-clearml-compute-gpu-002:0 DEBUG I0609 11:05:12.219801 697 libtorch.cc:940] TRITONBACKEND_Initialize: pytorch
I0609 11:05:12.219831 697 libtorch.cc:950] Triton TRITONBACKEND API version: 1.0
I0609 11:05:12.219841 697 libtorch.cc:956] 'pytorch' TRITONBACKEND API version: 1.0
2021-06-09 11:05:13.402667: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0

1623236719556 ecm-clearml-compute-gpu-002:0 DEBUG I0609 11:05:14.829180 697 tensorflow.cc:1880] TRITONBACKEND_Initialize: tensorflow
I0609 11:05:14.829213 697 tensorflow.cc:1890] Triton TRITONBACKEND API version: 1.0
I0609 11:05:14.833085 697 tensorflow.cc:1896] 'tensorflow' TRITONBACKEND API version: 1.0
I0609 11:05:14.833104 697 tensorflow.cc:1920] backend configuration:
{}
I0609 11:05:15.015101 697 onnxruntime.cc:1728] TRITONBACKEND_Initialize: onnxruntime
I0609 11:05:15.018722 697 onnxruntime.cc:1738] Triton TRITONBACKEND API version: 1.0
I0609 11:05:15.018742 697 onnxruntime.cc:1744] 'onnxruntime' TRITONBACKEND API version: 1.0
I0609 11:05:15.445218 697 openvino.cc:1166] TRITONBACKEND_Initialize: openvino
I0609 11:05:15.445250 697 openvino.cc:1176] Triton TRITONBACKEND API version: 1.0
I0609 11:05:15.445260 697 openvino.cc:1182] 'openvino' TRITONBACKEND API version: 1.0
I0609 11:05:15.876556 697 pinned_memory_manager.cc:205] Pinned memory pool is created at '0x7f4f2c000000' with size 268435456
I0609 11:05:15.881904 697 cuda_memory_manager.cc:103] CUDA memory pool is created on device 0 with size 67108864
I0609 11:05:15.910194 697 model_repository_manager.cc:1065] loading: cub200_resnet34:1
I0609 11:05:16.010648 697 libtorch.cc:989] TRITONBACKEND_ModelInitialize: cub200_resnet34 (version 1)
I0609 11:05:16.031903 697 libtorch.cc:1030] TRITONBACKEND_ModelInstanceInitialize: cub200_resnet34 (device 0)

1623236739858 ecm-clearml-compute-gpu-002:0 DEBUG I0609 11:05:39.787667 697 libtorch.cc:1063] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0609 11:05:39.787712 697 libtorch.cc:1012] TRITONBACKEND_ModelFinalize: delete model state
E0609 11:05:39.787741 697 model_repository_manager.cc:1242] failed to load 'cub200_resnet34' version 1: Unavailable: unable to find '/models/cub200_resnet34/1/model.pt' for model instance 'cub200_resnet34'
I0609 11:05:39.787824 697 server.cc:500] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0609 11:05:39.787889 697 server.cc:527] 
+-------------+-----------------------------------------------------------------+--------+
| Backend     | Path                                                            | Config |
+-------------+-----------------------------------------------------------------+--------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}     |
| tensorflow  | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {}     |
| openvino    | /opt/tritonserver/backends/openvino/libtriton_openvino.so       | {}     |
+-------------+-----------------------------------------------------------------+--------+

I0609 11:05:39.787931 697 server.cc:570] 
+-----------------+---------+--------------------------------------------------------------------------------------------------------------------+
| Model           | Version | Status                                                                                                             |
+-----------------+---------+--------------------------------------------------------------------------------------------------------------------+
| cub200_resnet34 | 1       | UNAVAILABLE: Unavailable: unable to find '/models/cub200_resnet34/1/model.pt' for model instance 'cub200_resnet34' |
+-----------------+---------+--------------------------------------------------------------------------------------------------------------------+

I0609 11:05:39.788016 697 tritonserver.cc:1658] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                              |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                             |
| server_version                   | 2.8.0                                                                                                                                              |
| server_extensions                | classification sequence model_repository schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | /models                                                                                                                                            |
| model_control_mode               | MODE_POLL                                                                                                                                          |
| strict_model_config              | 1                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                          |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                           |
| min_supported_compute_capability | 6.0                                                                                                                                                |
| strict_readiness                 | 1                                                                                                                                                  |
| exit_timeout                     | 30                                                                                                                                                 |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+

I0609 11:05:39.788048 697 server.cc:233] Waiting for in-flight requests to complete.
I0609 11:05:39.788061 697 server.cc:248] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models

1623236749930 ecm-clearml-compute-gpu-002:0 DEBUG Traceback (most recent call last):
  File "clearml_serving/triton_helper.py", line 214, in <module>
    main()
  File "clearml_serving/triton_helper.py", line 206, in main
    helper.maintenance_daemon(
  File "clearml_serving/triton_helper.py", line 126, in maintenance_daemon
    raise ValueError("triton-server process ended with error code {}".format(error_code))
ValueError: triton-server process ended with error code 1

1623236749966 ecm-clearml-compute-gpu-002:0 DEBUG Process failed, exit code 1
```

**Comment by ecm200** [comment]
@jkhenning 

I think I might be close to getting to the bottom of this issue with the model not being downloaded.
In the `triton_model_service_update_step` method of the `ServingService` Class, the method attempts to get a locally cached copy of the model for use with the serving engine. The try except block attempts to do this, however it fails on the `get_local_copy()` method of the `InputModel` Class object. The error reporting to terminal is simply the result of that issue.

I ran these commands locally directly on the compute machine:

```python
from clearml import Task, Model, InputModel
model = InputModel("57ed24c1011346d292ecc9e797ccb47e")
```

Getting the model url returned the correct remote path:

`azure://clearmllibrary/artefacts/Caltech Birds%2FTraining/TRAIN [Network%3A resnet34, Library%3A torchvision] Ignite Train PyTorch CNN on CUB200.8611ada5be6f4bb6ba09cf730ecd2253/models/cub200_resnet34_ignite_best_model_0.pt`

However, when I then tried the `get_local_copy()` method of the InputModel Class object, it failed with following reference to Azure Credentials:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edmorris/.conda/envs/py38_clearml_serving_git_dev/lib/python3.8/site-packages/clearml/model.py", line 424, in get_local_copy
    return self.get_weights(raise_on_error=raise_on_error)
  File "/home/edmorris/.conda/envs/py38_clearml_serving_git_dev/lib/python3.8/site-packages/clearml/model.py", line 285, in get_weights
    return self._get_base_model().download_model_weights(raise_on_error=raise_on_error)
  File "/home/edmorris/.conda/envs/py38_clearml_serving_git_dev/lib/python3.8/site-packages/clearml/backend_interface/model.py", line 403, in download_model_weights
    local_download = StorageManager.get_local_copy(uri, extract_archive=False)
  File "/home/edmorris/.conda/envs/py38_clearml_serving_git_dev/lib/python3.8/site-packages/clearml/storage/manager.py", line 46, in get_local_copy
    cached_file = cache.get_local_copy(remote_url=remote_url, force_download=force_download)
  File "/home/edmorris/.conda/envs/py38_clearml_serving_git_dev/lib/python3.8/site-packages/clearml/storage/cache.py", line 33, in get_local_copy
    helper = StorageHelper.get(remote_url)
  File "/home/edmorris/.conda/envs/py38_clearml_serving_git_dev/lib/python3.8/site-packages/clearml/storage/helper.py", line 227, in get
    base_url = cls._resolve_base_url(url)
  File "/home/edmorris/.conda/envs/py38_clearml_serving_git_dev/lib/python3.8/site-packages/clearml/storage/helper.py", line 831, in _resolve_base_url
    raise StorageError("Can't find azure configuration for {}".format(base_url))
clearml.storage.helper.StorageError: Can't find azure configuration for azure://clearmllibrary/artefacts/Caltech Birds%2FTraining/TRAIN [Network%3A resnet34, Library%3A torchvision] Ignite Train PyTorch CNN on CUB200.8611ada5be6f4bb6ba09cf730ecd2253/models/cub200_resnet34_ignite_best_model_0.pt
```

I have checked the `clearml.conf `file I used for executing the `clearml-agent` for the default services queue on the compute machine, as it does have credentials in there for the Azure Blob Storage container. These are the same credentials that I have successfully used during the training of models, also run on this compute node, to access the published version of the training and test datasets, which were successfully cached from the Azure Blob Storage location before model training. Therefore I am not entirely sure why it failing with credentials with this task.

It's also worth noting that one previous issue I ran into with regards to the Azure Blob Storage functionality was having the correct Azure Python SDK packages installed in the remote execution environment, otherwise similar errors would occur. I have attempted to account for this by installing the required packages in the environment by passing them through the `Task.create()` method call to create the Triton Inference service, in the `ServingService` Class method `launch_engine()`

**Comment by ecm200** [comment]
You probably know this, but I have forked the clearml-serving repo here, so you can easily see my changes in their entirety.

https://github.com/ecm200/clearml-serving

**Comment by ecm200** [comment]
Model weights download from the Azure Blob Store was found to be due to an incorrectly formatted `clearml.conf` file, which resulted in a non-standard structured dictionary on read in. Regeneration of the file and editing custom options as before resulted in successful connection to the Azure Blob Store and download of the model.

**Comment by ecm200** [comment]
Issue with the local copying of models was found in the `triton_model_service_update_step` method of the `ServingService` class.

The copying of the cached model to the directory structure setup for the Triton Inference Server results in the weights file inheriting the name from the cached model, instead of the expected `model.pth` file that the Triton server is trying to load.

A [temporary fix was applied in my fork](https://github.com/ecm200/clearml-serving/blob/7e89b8c0df14d05e760f0dc0ce1d916ed79a1b00/clearml_serving/serving_service.py#L578), which appears to allow the Triton server to find the model:

```python
new_target_path = Path(os.path.join(target_path.parent),'model.pt')
shutil.move(target_path.as_posix(), new_target_path.as_posix())
```

**Comment by bmartinn** [comment]
Hi @ecm200 
Based on the log
> E0610 15:20:59.633206 671 model_repository_manager.cc:1242] failed to load 'cub200_resnet34' version 1: Internal: failed to load model 'cub200_resnet34': [enforce fail at inline_container.cc:227] . file not found: archive/constants.pkl

I have a feeling this has something to do with:
https://github.com/pytorch/pytorch/issues/47917

wdyt?

**Comment by ecm200** [comment]
@bmartinn I am going to close this issue, as the original issue with ports and getting the Triton container running was solved with my previous comments on the modification of the `Task.create()` call to run the `Triton Serving Engine` task.

I think this PyTorch model loading issue is a separate one.

**Comment by ecm200** [comment]
@bmartinn on second thoughts, we might want to leave this open until the fixes have been applied to the main repo.
I was getting carried away as they are working in my fork!

Happy to fork the repo again, and make the specific changes and file a PR.

**Comment by ecm200** [comment]
### Found reason for ports conflict

For the compute nodes, I have been using my standard data science linux image, which comes with CUDA and JupyterHub pre-installed and running as a service.

Jupyterhub accepts incoming requests on port 8000 and would appear to listening on port 8001 as well.
Prior to terminating the service, I did a `sudo lsof -i -P -n` command, and can clearly see the ports being used.
Following terminating of the JupyterHub service [ `sudo service jupyterhub stop` ], these two ports were no longer being listened to, confirmed by not being in the list from the previous command.

I was then able to load the Triton server with the ports commands with docker.
`docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -v/home/edmorris/models_repo/cub200/resnet34:/models nvcr.io/nvidia/tritonserver:21.03-py3 tritonserver --model-repository=/models`

**Comment by ecm200** [comment]
This therefore means that the original issue of ports is not a clearml-serving issue, and this modification to the Task.create() call to create the Triton Serving Engine service is not needed.

I have rerun the Triton Inference container with `--ipc=host` in addition to the port mappings, and this seems to be behaving, so the [original call on line 203](https://github.com/allegroai/clearml-serving/blob/b6355a1db8da307750e37e9cb37a5fc23876c8dd/clearml_serving/serving_service.py#L203) of the `serving_service.py` should be fine.

**Comment by bmartinn** [comment]
Hi @ecm200 
This all makes total sense.
Following the suggestion here ( #2 ), I think we should add both Triton container image argument, as well as container execution args and Triton server args. These should enable you to fully control the remote container setup.

**Comment by ecm200** [comment]
> Hi @ecm200
> This all makes total sense.
> Following the suggestion here ( #2 ), I think we should add both Triton container image argument, as well as container execution args and Triton server args. These should enable you to fully control the remote container setup.

I concur, I think if you can make the Triton server configuration accessible for people that want to customize, but then have a set of reasonably intelligent and flexible defaults, for example like catching the requirement for cloud provider SDKs for remote storage access of models, that means the server can run out-of-box, then you will get the best of both worlds.

**Comment by ecm200** [comment]
One thing to note with the config.pbtxt.
My original file had this format:

```yaml
            platform: "pytorch_libtorch"
            input [
                {
                    name: "input_layer"
                    data_type: TYPE_FP32
                    dims: [ 3, 224, 224 ]
                }
            ]
            output [
                {
                    name: "fc"
                    data_type: TYPE_FP32
                    dims: [ 200 ]
                }
            ]
```

However, I had some issues with the Triton server accepting this when serving it images over HTTP.
I ended up modifying the configuration to the following, most notably the input and output NAME fields appeared to be non-descript relative to the model and just needed to be specified as this, and the dims fields were changed to single lines for each dimension:

```yaml
            platform: "pytorch_libtorch"
            input [
                {
                    name: "INPUT__0"
                    data_type: TYPE_FP32
                    dims: -1
                    dims: 3
                    dims: 224
                    dims: 224
                }
            ]
            output [
                {
                    name: "OUTPUT__0"
                    data_type: TYPE_FP32
                    dims: -1
                    dims: 200 
                }
            ]

**Comment by bmartinn** [comment]
> for example like catching the requirement for cloud provider SDKs for remote storage access of models, that means the server can run out-of-box, then you will get the best of both worlds.

Yep that's the plan :)

> most notably the input and output NAME fields appeared to be non-descript relative to the model and just needed to be specified as this

I "think" this has to match the layer name as stored inside the `model.pt`, this is how you tell Triton where it should push the input matrix or retrieve the results. Regrading the additional dimension, this is for the Triton batching support.
BTW it could it be the TorchScript changed the naming when it compiled the original model?

**Comment by qwaxys** [comment]
Closing this issue as inactive, feel free to open a new issue and link to this one.
