### ISSUE TITLE
Serving with custom engine

### ISSUE THREAD

**Issue by Bunoviske** [allegroai/clearml-serving#33]
Hello,

I checked the pipeline example where you use custom engine, but it is not very complete. What if I want to run normal pytorch inference without any engine? 

Is it also possible to implement my own Rest API (e.g. Flask) or at least have more control how I process my inferences? In your README.md, it says: `Customizable RestAPI for serving (i.e. allow per model pre/post-processing for easy integration)`. How can a really customize the RestAPI?

Thanks!
Bruno

**Comment by bmartinn** [comment]
Hi @Bunoviske 

> I checked the pipeline example where you use custom engine
Yes it is in he to do list to add a specific custom model serving example. I'll update here once it is up

> What if I want to run normal pytorch inference without any engine?
So you can just do "pytorch inference" as a custom engine (basically import pytorch and run the model. That said Triton is so much faster than just using vanilla pytorch for inference, and this is basically out of the box. Any reason for manually running the model inference ?

> Customizable RestAPI for serving (i.e. allow per model pre/post-processing for easy integration). How can a really customize the RestAPI?
The idea is the fact you can have any python code as pre/post processing, which really customize the entire API.  For example, RestAPI gets a url as string, and the preprocessing would download it, return a numpy object, then the inference is done on the image.
What exactly are you aiming for with the customization?

**Comment by Bunoviske** [comment]
Hello Martin!

No particular reason, I just wanted to understand how flexibel ClearML Serving is. Regarding your second question, I think I already got good outcome from our slack conversation and here: #32 

Once you have the new example with custom engine, let me know! Thanks :)

**Comment by bmartinn** [comment]
Quick update @Bunoviske 
You can now find a custom serving example [here](https://github.com/allegroai/clearml-serving/blob/main/examples/custom/readme.md) 😃
