### ISSUE TITLE
 better explanation of the scalar type and buckets 

### ISSUE THREAD

**Issue by besrym** [allegroai/clearml-serving#40]
Hi there, today I struggled with the (--variable-scalar) argument and the buckets in the `clearml-serving metrics add` command. 

I think the [documentation](https://clear.ml/docs/latest/docs/clearml_serving/clearml_serving_cli#add) could be improved.

I already got help in the ClearML Slack:

_A scalar in buckets is simply a histogram. Because if you have 1000s of requests per second, it makes no sense to display every data point. So scalars can be divided into buckets and for each minute, for example, we can calculate how much % of total traffic fell in bucket 1, bucket 2, bucket 3, etc. Then we display this histogram as a single column in a heatmap. Y axis is the buckets, color is the value ~ % of traffic in that bucket, and X is time._

**Comment by ainoam** [comment]
Much appreciated @besrym.

Are you up for a [PR](https://github.com/allegroai/clearml-docs/blob/main/docs/clearml_serving/clearml_serving_cli.md)?

**Comment by besrym** [comment]
Done!

https://github.com/allegroai/clearml-docs/pull/440
