### ISSUE TITLE
Configure options for gRPC (Triton server)

### ISSUE THREAD

**Issue by amirhmk** [allegroai/clearml-serving#49]
Hello! I am trying to play around with the configs for `gRPC` for the `triton` server. 

I’m using the `docker-compose` setup, so not sure if the CLI will work for my usecase (perhaps passing them as env variables would work?)

For instance, I’d like to set some variables like this:

```
('grpc.max_send_message_length', 512 * 1024 * 1024), ('grpc.max_receive_message_length', 512 * 1024 * 1024)]
```

Is this possible currently? I’m getting an error from gRPC that my payload is more than the limit (8MB instead of 4MB…)

#2

**Comment by pollfly** [comment]
Hey @amirhmk! [v1.3.0](https://github.com/allegroai/clearml-serving/releases/tag/1.3.0) is now out supporting gPRC channel configuration

**Comment by jkhenning** [comment]
@amirhmk I'm closing the issue. Please reopen if required.
