### ISSUE TITLE
Triton cannot find downloaded model

### ISSUE THREAD

**Issue by ecm200** [allegroai/clearml-serving#6]
Following commit b5f5d72 , the fixes regarding the container arguments and the cloud service python SDK's were resolved, howeve the Triton server still cannot find the downloaded model from Azure Blob Store locally.

This is because the name of the file is inherited from the Azure filename, rather than the expected "model.pt" that Triton is looking for. The model is placed in the correct folder structure, just not the correct name.

I successfully resolved this in my fork, by placing the following at the end of the `triton_model_service_update_step `method of the `ServingService `class.

```python
new_target_path = Path(os.path.join(target_path.parent),'model.pt')
shutil.move(target_path.as_posix(), new_target_path.as_posix())
```

**Comment by bmartinn** [comment]
Interesting point, from [here](https://github.com/triton-inference-server/server/blob/main/docs/model_repository.md) it looks as if this is somewhat "hardcoded" into Triton.
I'm thinking maybe we should auto-rename the model-file based on the backend (which should be in the `config.pbtxt`under `platform`).
wdyt?

**Comment by ecm200** [comment]
### Triton server configuration file and model file names

[Triton documentation](https://github.com/triton-inference-server/server/blob/r21.05/docs/model_repository.md#repository-layout) says that the model repository must take the following format:

```yaml
  <model-repository-path>/
    <model-name>/
      [config.pbtxt]
      [<output-labels-file> ...]
      <version>/
        <model-definition-file>
      <version>/
        <model-definition-file>
      ...
    <model-name>/
      [config.pbtxt]
      [<output-labels-file> ...]
      <version>/
        <model-definition-file>
      <version>/
        <model-definition-file>
      ...
    ...

```

For [Torchscript models specifically](https://github.com/triton-inference-server/server/blob/r21.05/docs/model_repository.md#torchscript-models), it specifies this format:

```yaml
  <model-repository-path>/
    <model-name>/
      config.pbtxt
      <version>/
        model.pt
```
The default name for the Torchscript model file is indeed "model.pt".
However, it does appear that these names can be overridden using the _default_model_filename_ parameter in the config.pbtxt file.

So, following from the [example config.pbtxt](https://github.com/allegroai/clearml-serving/issues/5#issuecomment-859649294) I shared in in issue #5, the updated config.pbtxt should look like:

```yaml
            name: "cub200_resnet34"
            default_model_filename: "cub200_resnet34_ignite_best_model_0_torchscript.pt"
            platform: "pytorch_libtorch"
            input [
                {
                    name: "INPUT__0"
                    data_type: TYPE_FP32
                    dims: -1
                    dims: 3
                    dims: 224
                    dims: 224
                }
            ]
            output [
                {
                    name: "OUTPUT__0"
                    data_type: TYPE_FP32
                    dims: -1
                    dims: 200
                }
            ]


**Given the directory structure of the serving model repository, I would imagine that it's probably easier to rename files to the default model name as nothing else will be placed in that folder. Even different versions will be served in different version folders and other models will be in their own directory structure.**

### Triton access to remote model repository

Also interesting to note that through the `--model-repository` flag on the Triton server call, you can specify remote locations for model repositories, on the cloud services like Azure, GCP and AWS.

For example, for Azure:

`tritonserver --model-repository=as://account_name/container_name/path/to/model/repository`

https://github.com/triton-inference-server/server/blob/r21.05/docs/model_repository.md#model-repository-locations

In this instance, perhaps local saving of model files is not a necessity as once these have been loaded to memory they are not accessed. So, once a Triton server goes live and loads models ready for inference, it only loads them from disk once. Therefore, specifying the remote location of the model file would be adequate enough to serve it, as it would be downloading the model directly. Not sure it makes a massive difference although it might be tidier?

**Comment by okyspace** [comment]
I seems to have the same problem. Triton cannot find any models. 
Tried @ecm200, but doesn't seems to work too. 

![image](https://user-images.githubusercontent.com/55354225/122446020-c7616f80-cfd4-11eb-9058-3753e69728c1.png)

**Comment by bmartinn** [comment]
First we will make sure we automatically configure/rename the models files (I will leave this Issue open until we do).
This should fix the issue in the next `clearml-serving` version

In the mean time, based on @ecm200 previous comment,  @okyspace you can specify in to your `config.pbtxt` the model file name for Triton to use (based on what you have in the ClearML model repository):
```yaml
default_model_filename: "your_model_file_here"
```

**Comment by bmartinn** [comment]
@ecm200 quick update, v2 is getting close to the finish line, already including torchscript example:
https://github.com/allegroai/clearml-serving/tree/dev/examples/pytorch

**Comment by qwaxys** [comment]
Closing this issue as inactive, feel free to open a new issue and link to this one.
