### ISSUE TITLE
Incorrect requests version specifier in requirements.txt 

### ISSUE THREAD

**Issue by ilyahabr** [allegroai/clearml-serving#66]
## Issue Description
Hi!
In the `requirements.txt` file, the `requests` version specifier is currently set to `>=2.31.0,<2.29.0`, which seems to be a mistake. And should be `>=2.29.0,<2.31.0`.
https://github.com/allegroai/clearml-serving/blob/main/clearml_serving/serving/requirements.txt

**Comment by jkhenning** [comment]
Hi @ilyahabr, thanks for noticing this.

Actually, this was caused by a snyk commit, and it was messed up a bit. The correct value should be `>=2.31.0,<2.32.0` - care to add a PR?

**Comment by ilyahabr** [comment]
Sure, I will create a PR

**Comment by ilyahabr** [comment]
Was solved
