### ISSUE TITLE
Behavior of published model

### ISSUE THREAD

**Issue by okyspace** [allegroai/clearml-serving#8]
Apologies that I may not have understood well as there are limited documentation. 

From the read me: 
"Notice: If we re-run our keras training example and publish a new model in the repository, the engine will automatically update to the new model."

I tested, when i first run my training but did not publish. When i start triton, this version is still avail in triton for inference. Is this correct? 

I also tried after start triton with version 1, i retrain the same model with same params. The triton polling indicates no change, thus did not pull the models over. Can I ask if this is the intended behavior?

**Comment by bmartinn** [comment]
Hi @okyspace 
> I tested, when i first run my training but did not publish. When i start triton, this version is still avail in triton for inference. Is this correct?

You absolutely correct, [here](https://github.com/allegroai/clearml-serving/blob/b5f5d72046f878bd09505606ca1147d93a5df069/clearml_serving/serving_service.py#L334) should be `only_published=True` 
Let me make sure we fix that (or at least add a flag to control it)

> The triton polling indicates no change, thus did not pull the models over.

How did you register the endpoint, with project/mode-name ? Any chance you can attach a log?

**Comment by okyspace** [comment]
Hi @bmartinn

This is how I create my serving service and then register an endpoint. 

```
clearml-serving triton --project "serving_engine_svs" --name "serving_engine_svs"

clearml-serving triton --project "serving_engine_svs" --name "serving_engine_svs" --endpoint "mnist_endpoint"  --model-project "mnist_example" --model-name "mnist_task - mnist_model"
```
Any idea where should I capture the useful logs? The triton logs basically shows this:

> Skipping update, nothing changed

**Comment by bmartinn** [comment]
> Once I add the model name to config file

What do you mean by that? Are you referring to the config.pbtxt ?

> ... last published version is still not available for inference.

I think I was able to confirm it. Can you test if the following works for you:
```
clearml-serving triton --model-tags deploy_me  --project "serving_engine_svs" --name "serving_engine_svs" --endpoint "mnist_endpoint"  --model-project "mnist_example" --model-name "mnist_task - mnist_model"
```
Then manually add the tag "deploy_me" to the selected models 
(basically it should only get models with the selected project/name and the specified tag)

**Comment by qwaxys** [comment]
Closing this issue as inactive, feel free to open a new issue and link to this one.
